# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install aspire workloads
        run: |
          dotnet workload update
          dotnet workload install aspire
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Generate package version
        run: echo "VERSION_SUFFIX=preview-2.${{github.run_number}}" >> $GITHUB_ENV
      - name: Create package
        if: github.ref == 'refs/heads/main'
        run: dotnet pack orchestration/src/FizzyLogic.Aspire.Python.Hosting/FizzyLogic.Aspire.Python.Hosting.csproj -o ./dist/ --version-suffix ${VERSION_SUFFIX}
      - name: Push package to NuGet feed
        if: github.ref == 'refs/heads/main'
        run: dotnet nuget push ./dist/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
